feat: add Github pages compatibility
rubensworks/rdf-test-suite.js pull request #91
Opened 2023-04-16 07:52 UTC by jitsedesmet

This PR aims to provide GitHub pages compatibility as discussed in https://github.com/comunica/sparqlee/pull/163 .

2023-04-16 07:53 UTC, jitsedesmet commented
Currently, 3 tests seem to be failing: 
```
 FAIL  test/e2e-test.ts (47.38 s)
  ● e2e tests on the test suite runner › parsing › it should correctly run [http://w3c.github.io/rdf-tests/trig/manifest.ttl]

    expect(received).toEqual(expected) // deep equality

    Expected: true
    Received: false

      87 |
      88 |         // All tests should either be ok or skipped
    > 89 |         expect(result.every(r => r.ok || r.skipped)).toEqual(true);
         |                                                      ^
      90 |       }, 190_000);
      91 |     }
      92 |   });

      at test/e2e-test.ts:89:54
      at fulfilled (test/e2e-test.ts:5:58)

  ● e2e tests on the test suite runner › parsing › it should correctly run [https://w3c.github.io/json-ld-streaming/tests/stream-toRdf-manifest.jsonld]

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected number of calls: 0
    Received number of calls: 18

    1: "TypeError: fetch failed"
    2: "TypeError: fetch failed"
    3: "TypeError: fetch failed"

      70 |         expect(console.log).not.toHaveBeenCalled();
      71 |         expect(console.warn).not.toHaveBeenCalled();
    > 72 |         expect(console.error).not.toHaveBeenCalled();
         |                                   ^
      73 |         expect(result.length).toBeGreaterThan(0);
      74 |
      75 |         let skipped = 0;

      at test/e2e-test.ts:72:35
      at fulfilled (test/e2e-test.ts:5:58)

  ● e2e tests on the test suite runner › query › should run correctly on [http://www.w3.org/TR/sparql11-query/]

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 6
    Received number of calls: 164

      114 |         expect(console.warn).not.toHaveBeenCalled();
      115 |         // One error for each of the tsv cases
    > 116 |         expect(console.error).toHaveBeenCalledTimes(6);
          |                               ^
      117 |
      118 |         expect(result.length).toBeGreaterThan(0)
      119 |

      at test/e2e-test.ts:116:31
      at fulfilled (test/e2e-test.ts:5:58)
```

2023-04-16 09:00 UTC, jitsedesmet commented
Strangely, I changed nothing and now all tests pass?

2023-04-17 08:35 UTC, rubensworks requested changes

2023-04-19 07:28 UTC, merged

2023-04-19 07:29 UTC, rubensworks commented
Thanks! Released as 1.23.1